flowchart TD

    U[User / Client]

    S3[Amazon S3<br/>Static Website]

    API[Amazon API Gateway<br/>REST API]

    AL[Lambda<br/>Allocation Handler]
    RL[Lambda<br/>Request Handler]
    RESL[Lambda<br/>Resource Handler]

    R[(DynamoDB<br/>Resources)]
    ER[(DynamoDB<br/>EmergencyRequests)]
    A[(DynamoDB<br/>Allocations)]

    EB[Amazon EventBridge<br/>ResourceAllocated Event]

    SNS[Amazon SNS<br/>EmergencyResourceNotifications]

    EMAIL[Email Notification]

    CW[Amazon CloudWatch<br/>Logs + Metrics + Alarm]

    IAM[AWS IAM<br/>Least-Privilege Permissions]

    BUDGET[AWS Budgets<br/>Cost Monitoring]

    U --> S3
    S3 --> API

    API -->|POST /allocate| AL
    API -->|GET /requests<br/>POST /requests| RL
    API -->|GET /allocate/resources| RESL
    API -->|GET /allocate/allocations| AL

    AL --> R
    AL --> ER
    AL --> A

    RL --> ER
    RESL --> R

    AL --> EB
    EB --> SNS
    SNS --> EMAIL

    AL --> CW
    RL --> CW
    RESL --> CW

    IAM -.-> AL
    IAM -.-> RL
    IAM -.-> RESL

    BUDGET -.-> S3
    BUDGET -.-> API
    BUDGET -.-> AL
    BUDGET -.-> RL
    BUDGET -.-> RESL
    BUDGET -.-> R
    BUDGET -.-> ER
    BUDGET -.-> A
    BUDGET -.-> EB
    BUDGET -.-> SNS